CREATE TABLE KontenAudio (
    id_konten	INT PRIMARY KEY NOT NULL,
    durasi	VARCHAR(512),
    kualitas	VARCHAR(512)
);

INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('101', '4:43', '320 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('102', '23:54', 'Lossless');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('109', '15:47', '96 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('110', '23:49', '256 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('146', '5:44', 'Lossless');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('147', '14:03', '128 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('159', '5:05', '96 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('170', '4:58', '320 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('173', '7:06', '320 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('182', '15:28', '128 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('196', '22:20', '320 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('199', '15:35', '320 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('206', '20:40', '96 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('211', '8:48', '128 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('217', '13:32', 'Lossless');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('227', '21:24', '320 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('229', '11:10', '256 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('239', '15:45', 'Lossless');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('256', '14:33', '96 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('259', '7:41', '256 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('277', '21:45', '128 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('319', '12:08', '96 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('337', '8:06', '256 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('341', '18:12', '96 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('343', '11:21', '256 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('351', '8:57', '320 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('354', '14:25', '320 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('360', '4:57', '320 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('377', '7:16', '96 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('404', '18:16', 'Lossless');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('420', '2:00', 'Lossless');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('482', '14:06', '96 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('524', '9:05', '256 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('544', '15:54', '128 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('579', '17:03', '96 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('594', '15:17', '128 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('616', '7:53', '320 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('619', '13:38', '128 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('659', '16:57', '96 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('666', '23:50', '128 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('696', '7:52', '256 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('706', '23:55', '320 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('708', '16:17', '96 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('730', '3:18', 'Lossless');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('736', '23:36', '256 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('746', '7:36', '96 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('766', '19:31', '96 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('778', '6:51', '128 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('784', '16:08', 'Lossless');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('842', '10:12', '320 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('849', '8:24', 'Lossless');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('862', '3:33', 'Lossless');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('863', '20:47', '320 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('891', '7:06', '320 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('896', '11:55', '256 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('902', '20:33', '96 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('911', '5:42', '128 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('924', '18:44', '256 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('934', '1:43', 'Lossless');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('953', '10:00', '320 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('957', '16:33', '96 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('964', '8:32', '128 kbps');
INSERT INTO KontenAudio (id_konten, durasi, kualitas) VALUES ('990', '18:57', 'Lossless');
