CREATE TABLE Merchandise (
    id_merchandise	VARCHAR(3) PRIMARY KEY NOT NULL,
    id_creator	VARCHAR(3) NOT NULL,
    id_konten	VARCHAR(3) NOT NULL,
    nama	VARCHAR(40),
    harga	INT,
    stok	INT,
    deskripsi	VARCHAR(512),
    FOREIGN KEY (id_creator) REFERENCES Membuat(id_creator)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (id_konten) REFERENCES Membuat(id_konten)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('100', 'AGT', '217', 'Cake mug', '37459', '70', 'Mug dengan desain unik, dapat digunakan untuk minum teh atau kopi sehari-hari.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('913', 'ATT', '826', 'T-shirt', '26278', '89', 'T-shirt dengan desain grafis yang modern dan menarik, cocok untuk acara santai.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('242', 'BRS', '436', 'Leather bracelet', '3014', '51', 'Gelang kulit dengan desain minimalis dan elegan, cocok untuk segala suasana.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('138', 'CTD', '391', 'Cartoonist socks', '46562', '24', 'Kaos kaki hangat dengan desain kartun yang lucu, nyaman dipakai di musim dingin.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('487', 'DHM', '736', 'Vintage hoodie', '7610', '76', 'Hoodie dengan desain vintage, cocok untuk kegiatan luar ruangan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('539', 'DNS', '725', 'Baseball cap', '9326', '91', 'Topi baseball dengan logo besar, cocok untuk gaya kasual.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('896', 'DWP', '685', 'Practical backpack', '7944', '21', 'Tas ransel dengan banyak kompartemen, sangat praktis untuk berpergian.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('878', 'JJK', '956', 'Floral tea cup', '1626', '39', 'Cangkir teh dengan desain floral, membuat minum teh semakin menyenangkan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('449', 'JLN', '911', 'Analog watch', '18800', '76', 'Jam tangan analog dengan desain klasik, cocok untuk acara formal atau kasual.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('120', 'JNL', '262', 'Sofa cushions', '11986', '85', 'Bantal sofa dengan kain lembut dan empuk, memberikan kenyamanan saat bersantai.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('899', 'LCL', '928', 'Running shoes', '25528', '55', 'Sepatu olahraga dengan teknologi terbaru, nyaman untuk lari dan aktivitas fisik.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('222', 'LDV', '103', 'Leather purse', '48811', '66', 'Dompet kulit dengan desain elegan, cocok untuk gaya profesional.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('274', 'MRB', '377', 'Water bottle', '5418', '12', 'Botol air dengan desain ergonomis, membuat minum lebih mudah di luar ruangan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('999', 'PDB', '205', 'Work lamp', '9771', '27', 'Lampu meja dengan desain minimalis, memberikan pencahayaan lembut untuk ruang kerja.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('967', 'RBC', '439', 'Folding chair', '32050', '95', 'Kursi lipat dengan bahan tahan lama, cocok untuk digunakan di luar ruangan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('883', 'RTM', '816', 'Phone case', '24978', '50', 'Casing ponsel dengan desain artistik, melindungi ponsel dan tampil stylish.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('444', 'SKP', '746', 'Pencil case', '19302', '81', 'Tempat pensil dengan desain lucu dan fungsional, cocok untuk anak-anak.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('642', 'SMS', '188', 'Slippers', '17261', '87', 'Sandal rumah dengan material lembut dan nyaman, pas digunakan di rumah.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('838', 'SSS', '536', 'Greeting card', '28359', '26', 'Kartu ucapan dengan desain ilustrasi indah, cocok untuk berbagai perayaan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('544', 'TRL', '694', 'Pajamas', '15354', '67', 'Baju tidur dengan bahan katun halus, nyaman untuk tidur yang nyenyak.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('186', 'TTS', '360', 'Wallet', '9002', '56', 'Dompet pria dengan desain ramping, praktis dan elegan untuk dibawa ke mana-mana.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('785', 'TVS', '355', 'Eyeglass lenses', '17442', '64', 'Lensa kacamata dengan teknologi anti-radiasi, melindungi mata dari layar komputer.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('812', 'TXT', '876', 'Gloves', '29872', '41', 'Sarung tangan kulit dengan desain modern, memberikan kenyamanan dan perlindungan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('933', 'WDB', '100', 'Black pen', '17735', '26', 'Pena stylish dengan tinta hitam berkualitas, nyaman digunakan untuk menulis.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('519', 'ZHC', '482', 'Windbreaker jacket', '17949', '47', 'Jaket windbreaker yang ringan dan tahan angin, cocok untuk kegiatan outdoor.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('799', 'AGT', '724', 'Scrunchie', '3525', '28', 'Tali pengikat rambut dengan desain warna-warni, praktis dan menarik.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('255', 'ATT', '683', 'Mini umbrella', '36689', '58', 'Payung mini dengan desain lipat, mudah dibawa dan digunakan saat hujan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('833', 'BRS', '588', 'Yoga footwear', '46880', '16', 'Alas kaki yoga dengan desain tebal, memberikan kenyamanan saat berlatih.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('605', 'CTD', '619', 'Sunglasses', '4926', '64', 'Kacamata hitam dengan bingkai modis, melindungi mata dari sinar UV.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('977', 'DHM', '759', 'Boots', '43026', '29', 'Sepatu boot dengan sol anti-selip, cocok untuk cuaca dingin dan basah.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('335', 'DNS', '831', 'Decorative lights', '35311', '44', 'Lampu hias dengan desain kreatif, menciptakan suasana cozy di dalam rumah.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('419', 'DWP', '107', 'Carpet', '38438', '66', 'Karpet bulu halus dengan desain kontemporer, menambah estetika ruang tamu.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('313', 'JJK', '277', 'Termometer', '14529', '23', 'Alat pengukur suhu dengan layar digital, mudah dibaca dan akurat.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('658', 'JLN', '680', 'Sleeping bag', '12094', '86', 'Kantong tidur dengan bahan lembut, cocok untuk berkemah atau tidur di luar.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('560', 'JNL', '339', 'Curtains', '23142', '81', 'Tirai jendela dengan desain elegan, memberikan privasi sekaligus dekorasi.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('601', 'LCL', '743', 'Pillow case', '27513', '52', 'Sarung bantal dengan motif warna-warni, cocok untuk menambah warna di rumah.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('259', 'LDV', '182', 'Charger cable', '25084', '39', 'Kabel charger dengan panjang ekstra, nyaman digunakan untuk berbagai perangkat.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('191', 'MRB', '113', 'Modular storage', '5507', '85', 'Tempat penyimpanan dengan desain modular, membuat ruang lebih terorganisir.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('663', 'PDB', '926', 'Swimsuit', '35989', '4', 'Baju renang dengan desain sport, ideal untuk aktivitas di kolam renang.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('930', 'RBC', '895', 'Plastic bottle', '37586', '26', 'Gelas plastik dengan desain simpel, cocok untuk piknik atau acara luar ruangan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('233', 'RTM', '199', 'High heels', '9528', '94', 'Sepatu hak tinggi dengan desain chic, sempurna untuk acara formal.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('645', 'SKP', '388', 'Car decoration', '49310', '65', 'Aksesori mobil dengan desain modern, menambah kenyamanan dan gaya pada kendaraan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('263', 'SMS', '973', 'Toaster', '36541', '74', 'Alat pemanggang roti dengan fungsi otomatis, cocok untuk sarapan cepat.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('951', 'SSS', '165', 'Shoelace', '15381', '75', 'Tali sepatu dengan bahan tahan lama, cocok untuk sepatu olahraga dan kasual.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('281', 'TRL', '354', 'Speaker', '6767', '3', 'Speaker Bluetooth dengan suara jernih, ideal untuk mendengarkan musik di mana saja.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('696', 'TTS', '873', 'Chair', '33560', '93', 'Kursi dengan desain ergonomis, nyaman digunakan untuk acara luar ruangan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('565', 'TVS', '396', 'Laptop backpack', '12756', '55', 'Ransel laptop dengan banyak ruang, praktis untuk membawa laptop dan barang lainnya.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('756', 'TXT', '623', 'Comb', '5102', '4', 'Sisir dengan bahan plastik kuat, cocok untuk berbagai jenis rambut.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('234', 'WDB', '173', 'Gold ring', '392460', '71', 'Cincin emas dengan desain elegan, ideal sebagai hadiah spesial.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('249', 'ZHC', '889', 'Wall art', '7496', '38', 'Hiasan dinding dengan desain unik, menambah estetika ruang tamu.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('576', 'AGT', '527', 'Mini telescope', '46979', '64', 'Teleskop kecil dengan desain portabel, cocok untuk pengamatan langit malam.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('779', 'ATT', '546', 'Tie', '7449', '36', 'Dasi dengan desain klasik, melengkapi penampilan formal Anda.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('401', 'BRS', '343', 'Sports whistle', '13084', '10', 'Peluit olahraga dengan suara keras, berguna untuk aktivitas luar ruangan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('358', 'CTD', '523', 'Tote bag', '14589', '51', 'Tas jinjing dengan desain simple, cocok untuk belanja atau berpergian.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('743', 'DHM', '563', 'Coffee mug', '45841', '92', 'Cangkir kopi dengan desain vintage, memberikan suasana santai di pagi hari.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('315', 'DNS', '998', 'Notebook', '17055', '25', 'Buku catatan dengan kertas berkualitas tinggi, ideal untuk mencatat ide atau pekerjaan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('786', 'DWP', '159', 'Book cover', '47925', '77', 'Sampul buku dengan desain artistik, melindungi buku kesayangan Anda.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('514', 'JJK', '962', 'Message tool', '15949', '45', 'Alat pemijat tangan dengan desain ergonomis, memberikan kenyamanan setelah lelah bekerja.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('611', 'JLN', '274', 'Thermos', '14549', '32', 'Thermos dengan desain praktis, menjaga suhu minuman lebih lama.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('957', 'JNL', '398', 'Laptop case', '15913', '64', 'Casing laptop dengan desain modern, melindungi laptop Anda dari goresan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('732', 'LCL', '211', 'Funny pencil box', '44319', '78', 'Tempat pensil dengan desain lucu, cocok untuk anak-anak atau pelajar.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('771', 'LDV', '555', 'Toiletries', '23357', '50', 'Perlengkapan mandi dengan desain minimalis, cocok untuk kamar mandi modern.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('777', 'MRB', '638', 'Ruler', '29877', '22', 'Penggaris dengan desain elegan, praktis untuk mengukur benda.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('661', 'PDB', '515', 'Towel', '49374', '25', 'Handuk mandi dengan bahan lembut, memberikan kenyamanan setelah mandi.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('770', 'RBC', '227', 'Coaster', '25712', '6', 'Tatakan gelas dengan desain unik, melindungi permukaan meja Anda dari noda.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('399', 'RTM', '982', 'Digital camera', '15141', '51', 'Kamera digital dengan kualitas tinggi, ideal untuk pemotretan profesional.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('216', 'SKP', '401', 'Picnic mat', '4241', '20', 'Tikar piknik dengan bahan tahan air, praktis digunakan di luar ruangan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('224', 'SMS', '830', 'Measuring cup', '7192', '61', 'Gelas ukur dengan tanda pengukur, sangat praktis untuk dapur.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('373', 'SSS', '862', 'Portable bed', '13024', '35', 'Tempat tidur lipat dengan desain portable, sangat cocok untuk penginapan sementara.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('155', 'TRL', '236', 'Mini fridge', '43933', '11', 'Kulkas mini dengan kapasitas besar, cocok untuk ruang kecil atau kamar tidur.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('144', 'TTS', '138', 'Bottle opener', '34224', '87', 'Alat pembuka botol dengan desain simpel, praktis untuk acara santai.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('429', 'TVS', '448', 'Rubber band', '26571', '97', 'Karet gelang dengan bahan elastis, dapat digunakan untuk berbagai keperluan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('852', 'TXT', '787', 'Fridge magnet', '39880', '62', 'Magnet kulkas dengan desain lucu, memberikan warna pada dapur.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('603', 'WDB', '869', 'Cool keychain', '4689', '55', 'Gantungan kunci dengan desain keren, sangat cocok untuk koleksi atau hadiah.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('626', 'ZHC', '953', 'Dog leash', '6167', '97', 'Tali anjing dengan pegangan ergonomis, cocok untuk pemilik hewan peliharaan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('433', 'AGT', '612', 'Rubbish bin', '29243', '86', 'Tempat sampah dengan desain modern, membuat kebersihan rumah tetap terjaga.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('286', 'ATT', '424', 'Cleaning tool', '11324', '42', 'Alat kebersihan dengan desain compact, sangat efisien digunakan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('424', 'BRS', '185', 'Tissue box', '15148', '65', 'Tempat tisu dengan desain minimalis, cocok untuk dekorasi ruang tamu.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('515', 'CTD', '659', 'Air freshener', '17963', '80', 'Pengharum ruangan dengan aroma menenangkan, cocok untuk di rumah.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('995', 'DHM', '166', 'Vegetable cutter', '21892', '96', 'Alat pemotong sayuran dengan desain tajam, mempermudah pekerjaan dapur.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('589', 'DNS', '737', 'Mini speaker', '43213', '61', 'Speaker mini dengan suara jernih, praktis untuk membawa musik ke mana saja.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('868', 'DWP', '566', 'Water heater', '34287', '65', 'Alat pemanas air dengan kapasitas besar, praktis untuk keluarga.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('404', 'JJK', '101', 'Glass cleaner', '36861', '55', 'Pembersih kaca dengan desain ergonomis, memudahkan pembersihan jendela.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('956', 'JLN', '662', 'Griller', '5656', '11', 'Pemanggang daging dengan desain portabel, cocok untuk acara barbekyu.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('499', 'JNL', '315', 'Clothing set', '8217', '67', 'Pakaian dengan bahan lembut, nyaman dipakai sehari-hari.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('982', 'LCL', '805', 'Mini fan', '38207', '44', 'Kipas angin mini dengan desain portabel, mudah dibawa kemana-mana.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('215', 'LDV', '594', 'Night lamp', '21679', '11', 'Lampu tidur dengan desain unik, memberikan pencahayaan lembut saat tidur.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('264', 'MRB', '406', 'Casual bracelet', '42695', '23', 'Gelang tangan dengan bahan stainless, cocok untuk tampilan kasual.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('223', 'PDB', '465', 'Kitchen set', '27448', '87', 'Peralatan dapur dengan desain sederhana, praktis untuk memasak sehari-hari.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('764', 'RBC', '120', 'Table lamp', '31984', '1', 'Lampu meja dengan cahaya yang menenangkan, ideal untuk ruangan tidur.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('379', 'RTM', '934', 'Wall clock', '16620', '44', 'Jam dinding dengan desain elegan, cocok untuk ruang tamu atau kantor.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('294', 'SKP', '745', 'Neck pillow', '18870', '71', 'Bantal leher dengan bahan empuk, ideal untuk perjalanan panjang.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('166', 'SMS', '234', 'Face mask', '2614', '2', 'Masker wajah dengan bahan lembut, memberikan kelembapan pada kulit.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('111', 'SSS', '556', 'Winter jacket', '3436', '32', 'Jaket dengan bahan tebal, cocok untuk cuaca dingin.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('277', 'TRL', '964', 'Slingbag', '45687', '37', 'Tas selempang dengan desain praktis, cocok untuk bepergian.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('537', 'TTS', '106', 'Sporty bottle', '44276', '85', 'Botol minum dengan desain sporty, praktis digunakan untuk olahraga.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('153', 'TVS', '342', 'Handphone case', '49346', '60', 'Handphone case dengan desain minimalis, melindungi ponsel dari goresan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('857', 'TXT', '512', 'Wall sticker', '42511', '24', 'Stiker dinding dengan desain menarik, cocok untuk dekorasi rumah.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('146', 'WDB', '706', 'Blouse', '16571', '13', 'Kemeja dengan bahan katun, nyaman dipakai untuk acara santai.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('997', 'ZHC', '395', 'Lunch box', '30329', '70', 'Tempat makan dengan desain praktis, ideal untuk dibawa bekerja.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('362', 'AGT', '791', 'Outdoor spotlight', '21846', '67', 'Lampu sorot dengan daya tinggi, cocok untuk keperluan outdoor.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('203', 'ATT', '635', 'Sleep mask', '22944', '100', 'Masker tidur dengan bahan halus, cocok untuk tidur yang lebih nyenyak.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('834', 'BRS', '730', 'Cute mug', '49145', '21', 'Mug dengan desain lucu, cocok untuk hadiah.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('532', 'CTD', '402', 'Tumbler', '36286', '22', 'Tumbler dengan desain kekinian, praktis untuk minum di perjalanan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('757', 'DHM', '834', 'Scarf', '3538', '59', 'Syal dengan bahan lembut, cocok untuk cuaca dingin.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('494', 'DNS', '381', 'Home toaster', '34989', '61', 'Alat pemanggang roti dengan fungsi otomatis, praktis digunakan di rumah.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('864', 'DWP', '351', 'Bed', '2916', '71', 'Ranjang dengan desain ergonomis, memberikan kenyamanan saat tidur.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('178', 'JJK', '307', 'Sport shirt', '49997', '74', 'Baju olahraga dengan bahan nyaman, ideal untuk kegiatan di luar ruangan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('979', 'JLN', '603', 'Sport camera', '37532', '98', 'Kamera olahraga dengan desain tahan air, cocok untuk kegiatan ekstrem.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('843', 'JNL', '438', 'Razor', '36054', '90', 'Alat cukur dengan desain modern, nyaman digunakan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('557', 'LCL', '206', 'Beanie', '38220', '85', 'Penutup kepala dengan desain keren, cocok untuk aktivitas outdoor.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('792', 'LDV', '283', 'Art cover', '27448', '51', 'Sampul buku dengan desain artistik, melindungi buku dengan gaya.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('862', 'MRB', '121', 'Knife sharpener', '22465', '74', 'Alat pengasah pisau dengan desain portabel, praktis digunakan di dapur.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('147', 'PDB', '944', 'Sofa', '37468', '31', 'Sofa dengan bahan lembut, nyaman digunakan saat bersantai.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('432', 'RBC', '666', 'Elegant tea cup', '31748', '72', 'Gelas teh dengan desain elegan, cocok untuk acara formal.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('414', 'RTM', '418', 'Table leg', '10502', '3', 'Kaki meja dengan desain kokoh, memberikan dukungan lebih pada meja.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('118', 'SKP', '916', 'Pendant light', '37125', '21', 'Lampu gantung dengan desain artistik, menambah keindahan ruang tamu.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('214', 'SMS', '999', 'Food container', '4801', '23', 'Kotak makan dengan desain unik, sangat praktis digunakan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('854', 'SSS', '524', 'Raincoat', '41462', '45', 'Jas hujan dengan desain ringan, melindungi Anda dari hujan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('889', 'TRL', '521', 'Unique phone case', '25247', '19', 'Casing ponsel dengan desain unik, melindungi ponsel dari goresan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('208', 'TTS', '286', 'Extra long charger', '38616', '9', 'Kabel charger dengan panjang ekstra, memudahkan Anda saat mengisi daya.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('934', 'TVS', '306', 'Many storage box', '12035', '59', 'Kotak penyimpanan dengan banyak ruang, cocok untuk rumah minimalis.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('209', 'TXT', '863', 'Laundry basket', '43475', '3', 'Keranjang laundry dengan desain praktis, mudah digunakan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('387', 'WDB', '714', 'Hot stone', '21457', '12', 'Batu pijat dengan desain alami, memberikan kenyamanan setelah beraktivitas.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('578', 'ZHC', '502', 'Decorative brick', '39065', '26', 'Batu bata dekoratif dengan desain modern, cocok untuk dinding rumah.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('359', 'AGT', '948', 'Personalize mug', '4740', '3', 'Mug dengan desain personalisasi, sangat cocok untuk hadiah.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('817', 'ATT', '337', 'Colorful slippers', '30841', '10', 'Sandal jepit dengan desain warna-warni, nyaman digunakan di rumah.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('822', 'BRS', '366', 'Modern lunch box', '19399', '71', 'Tempat makan dengan desain modern, cocok untuk berbagai acara.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('374', 'CTD', '663', 'Casual sandals', '30096', '65', 'Sandal dengan bahan berkualitas, nyaman digunakan sehari-hari.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('180', 'DHM', '773', 'Jewelry box', '41605', '49', 'Kotak perhiasan dengan desain elegan, cocok untuk koleksi perhiasan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('218', 'DNS', '102', 'Hanger', '2918', '42', 'Gantungan baju dengan desain unik, cocok untuk ruang tamu.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('103', 'DWP', '819', 'Modern cap', '41269', '36', 'Topi dengan desain modern, melindungi dari sinar matahari.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('305', 'JJK', '479', 'Unique mug', '13398', '81', 'Mug dengan desain unik, dapat digunakan untuk minum teh atau kopi sehari-hari.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('670', 'JLN', '540', 'Art shirt', '47295', '8', 'T-shirt dengan desain grafis yang modern dan menarik, cocok untuk acara santai.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('683', 'JNL', '170', 'Friendhip bracelet', '16526', '81', 'Gelang kulit dengan desain lucu, cocok untuk bersama dengan teman.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('859', 'LCL', '613', 'Warm socks', '7297', '86', 'Kaos kaki hangat dengan desain kartun yang lucu, nyaman dipakai di musim dingin.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('148', 'LDV', '742', 'Hoodie', '43922', '9', 'Hoodie dengan desain vang keren, cocok untuk kegiatan luar ruangan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('652', 'MRB', '358', 'Basket hat', '41016', '45', 'Topi basket dengan logo yang keren, cocok untuk gaya kasual.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('918', 'PDB', '196', 'Backpack', '40327', '26', 'Tas dengan desain ergonomis yang memudahkan membawa banyak barang tanpa rasa lelah.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('767', 'RBC', '872', 'Cup', '17219', '36', 'Cangkir dengan bentuk unik yang cocok untuk menikmati minuman favorit kapan saja.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('101', 'RTM', '486', 'Watch', '13779', '13', 'Jam tangan dengan tampilan sederhana namun tetap elegan untuk aktivitas sehari-hari.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('310', 'SKP', '162', 'Pillow', '1108', '35', 'Bantal yang dirancang khusus untuk mendukung punggung dan kepala saat bersantai.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('278', 'SMS', '420', 'Shoes', '42802', '10', 'Sepatu yang ringan dan fleksibel, cocok untuk berbagai olahraga dan aktivitas luar ruangan.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('538', 'SSS', '716', 'Quality wallet', '6636', '65', 'Dompet yang terbuat dari bahan berkualitas tinggi, menjaga barang berharga tetap aman.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('529', 'TRL', '327', 'Ideal bottle', '30586', '74', 'Botol minum yang tahan lama dan mudah dibersihkan, ideal untuk penggunaan harian.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('769', 'TTS', '495', 'Study lamp', '36982', '45', 'Lampu dengan cahaya hangat yang menciptakan suasana nyaman di ruangan belajar.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('483', 'TVS', '957', 'Picnic chair', '38099', '46', 'Kursi portable yang mudah dibawa dan cepat dilipat, cocok untuk piknik.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('606', 'TXT', '871', 'Hard case', '22981', '48', 'Casing ponsel dengan bahan tahan benturan yang melindungi dari goresan dan jatuh.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('446', 'WDB', '542', 'Compact pencil case', '5306', '91', 'Tempat pensil yang kompak dan kuat, menjaga alat tulis tetap teratur dan mudah dijangkau.');
INSERT INTO Merchandise (id_merchandise, id_creator, id_konten, nama, harga, stok, deskripsi) VALUES ('662', 'ZHC', '997', 'Soft sandals', '2274', '61', 'Sandal untuk dipakai di dalam rumah dengan bantalan empuk yang menjaga kaki tetap nyaman saat berjalan santai.');

