CREATE TABLE OrderSpecialContent (
    id_order	INT,
    id_suporter	INT,
    id_creator	VARCHAR(512),
    judul	VARCHAR(512),
    deskripsi	VARCHAR(512),
    harga_dasar	INT,
    tgl_batas_revisi	VARCHAR(512),
    status_pengerjaan	VARCHAR(512),
    estimasi_pengerjaan	INT,
    tanggal_penyelesaian	VARCHAR(512),
    id_konten	VARCHAR(512),
    feedback	VARCHAR(512)
);

INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('1', '4', 'BRS', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '878012', '2023-04-17', 'dalam_pengerjaan', '8', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('2', '17', 'BRS', 'Visualisasi Karakter RPG', 'Desain karakter untuk proyek game role-playing.', '289584', '2025-04-17', 'menunggu_persetujuan', '7', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('3', '3', 'ZHC', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '1355541', '2025-05-26', 'menunggu_persetujuan', '20', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('4', '7', 'ZHC', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '1486971', '2025-03-26', 'menunggu_persetujuan', '23', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('5', '19', 'ZHC', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '997771', '2024-09-24', 'dalam_pengerjaan', '21', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('6', '17', 'ZHC', 'Ilustrasi Karakter Fantasi', 'Gambarkan karakter orisinal dengan tema dunia fantasi.', '275121', '2023-09-26', 'ditolak', '29', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('7', '20', 'BRS', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '1487298', '2023-05-21', 'disetujui', '14', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('8', '8', 'ZHC', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '1234294', '2024-10-15', 'dalam_pengerjaan', '7', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('9', '15', 'ZHC', 'Konsep Art Makhluk Fantasi', 'Makhluk mitologi atau imajinatif dalam bentuk digital.', '1181819', '2024-02-27', 'dalam_pengerjaan', '4', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('10', '23', 'ZHC', 'Visualisasi Karakter RPG', 'Desain karakter untuk proyek game role-playing.', '611138', '2025-08-07', 'menunggu_persetujuan', '6', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('11', '12', 'LDV', 'Ilustrasi Tema Musik', 'Ilustrasi karakter dengan suasana konser atau musik.', '614183', '2023-04-30', 'ditolak', '21', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('12', '14', 'BRS', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '1022057', '2025-01-10', 'menunggu_persetujuan', '17', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('13', '22', 'LDV', 'Chibi Karakter Band', 'Versi chibi lucu dari empat anggota band virtual.', '228360', '2025-05-10', 'menunggu_persetujuan', '15', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('14', '11', 'LDV', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '666489', '2025-02-07', 'menunggu_persetujuan', '22', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('15', '24', 'ZHC', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '1135374', '2024-10-21', 'disetujui', '6', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('16', '24', 'BRS', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '596525', '2023-11-06', 'ditolak', '14', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('17', '5', 'LDV', 'Lukisan Digital Pemandangan', 'Lukisan pemandangan alam dengan gaya semi-realistis.', '714606', '2024-09-12', 'dalam_pengerjaan', '14', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('18', '21', 'ZHC', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '564657', '2023-06-28', 'ditolak', '19', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('19', '11', 'BRS', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '648669', '2025-10-13', 'selesai', '10', '2025-10-10', '571', 'Proses cepat dan komunikatif.');
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('20', '10', 'LDV', 'Ilustrasi Karakter Fantasi', 'Gambarkan karakter orisinal dengan tema dunia fantasi.', '1332549', '2023-12-14', 'disetujui', '7', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('21', '23', 'ZHC', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '1209226', '2023-10-05', 'ditolak', '26', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('22', '23', 'LDV', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '982213', '2023-08-31', 'ditolak', '5', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('23', '5', 'LDV', 'Ilustrasi Karakter Fantasi', 'Gambarkan karakter orisinal dengan tema dunia fantasi.', '1230465', '2025-06-01', 'menunggu_persetujuan', '5', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('24', '19', 'BRS', 'Konsep Art Makhluk Fantasi', 'Makhluk mitologi atau imajinatif dalam bentuk digital.', '174822', '2025-07-25', 'menunggu_persetujuan', '8', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('25', '4', 'BRS', 'Visualisasi Karakter RPG', 'Desain karakter untuk proyek game role-playing.', '241859', '2023-11-05', 'ditolak', '10', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('26', '3', 'BRS', 'Chibi Karakter Band', 'Versi chibi lucu dari empat anggota band virtual.', '919312', '2023-02-22', 'dalam_pengerjaan', '29', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('27', '23', 'BRS', 'Visualisasi Karakter RPG', 'Desain karakter untuk proyek game role-playing.', '690787', '2025-08-16', 'selesai', '22', '2025-08-01', '610', 'Hasil sangat memuaskan dan profesional!');
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('28', '5', 'ZHC', 'Chibi Karakter Band', 'Versi chibi lucu dari empat anggota band virtual.', '1089442', '2025-06-06', 'menunggu_persetujuan', '24', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('29', '25', 'BRS', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '892615', '2023-09-19', 'disetujui', '22', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('30', '17', 'LDV', 'Konsep Art Makhluk Fantasi', 'Makhluk mitologi atau imajinatif dalam bentuk digital.', '287385', '2024-10-02', 'dalam_pengerjaan', '24', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('31', '4', 'LDV', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '1474260', '2023-09-21', 'ditolak', '7', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('32', '1', 'ZHC', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '473017', '2025-03-08', 'selesai', '18', '2025-03-02', '241', 'Proses cepat dan komunikatif.');
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('33', '12', 'ZHC', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '494766', '2024-11-22', 'selesai', '5', '2024-11-20', '560', 'Revisi langsung dikerjakan, mantap.');
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('34', '18', 'ZHC', 'Lukisan Digital Pemandangan', 'Lukisan pemandangan alam dengan gaya semi-realistis.', '949715', '2023-01-27', 'ditolak', '18', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('35', '12', 'BRS', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '837374', '2024-10-21', 'dalam_pengerjaan', '15', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('36', '14', 'ZHC', 'Ilustrasi Karakter Fantasi', 'Gambarkan karakter orisinal dengan tema dunia fantasi.', '1095375', '2025-08-16', 'menunggu_persetujuan', '20', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('37', '22', 'ZHC', 'Ilustrasi Tema Musik', 'Ilustrasi karakter dengan suasana konser atau musik.', '443824', '2025-10-30', 'selesai', '18', '2025-10-28', '108', NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('38', '11', 'BRS', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '505734', '2024-12-22', 'menunggu_persetujuan', '30', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('39', '2', 'BRS', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '1363818', '2024-09-03', 'dalam_pengerjaan', '17', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('40', '7', 'BRS', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '745541', '2025-09-04', 'selesai', '15', '2025-09-01', '530', 'Ilustrasinya keren, sesuai request!');
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('41', '5', 'ZHC', 'Lukisan Digital Pemandangan', 'Lukisan pemandangan alam dengan gaya semi-realistis.', '865627', '2023-06-29', 'ditolak', '20', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('42', '16', 'LDV', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '1217320', '2024-02-17', 'disetujui', '20', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('43', '18', 'BRS', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '13283', '2025-03-07', 'menunggu_persetujuan', '29', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('44', '7', 'ZHC', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '1041798', '2024-02-12', 'dalam_pengerjaan', '9', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('45', '4', 'LDV', 'Visualisasi Karakter RPG', 'Desain karakter untuk proyek game role-playing.', '1155845', '2023-01-31', 'ditolak', '27', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('46', '21', 'BRS', 'Chibi Karakter Band', 'Versi chibi lucu dari empat anggota band virtual.', '1122794', '2025-06-11', 'menunggu_persetujuan', '30', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('47', '19', 'ZHC', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '772218', '2024-03-08', 'dalam_pengerjaan', '8', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('48', '5', 'BRS', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '1401994', '2025-04-30', 'menunggu_persetujuan', '19', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('49', '22', 'BRS', 'Ilustrasi Karakter Fantasi', 'Gambarkan karakter orisinal dengan tema dunia fantasi.', '893936', '2023-12-23', 'dalam_pengerjaan', '25', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('50', '1', 'BRS', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '402486', '2024-08-13', 'disetujui', '30', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('51', '22', 'BRS', 'Konsep Art Makhluk Fantasi', 'Makhluk mitologi atau imajinatif dalam bentuk digital.', '571075', '2024-07-21', 'disetujui', '16', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('52', '24', 'LDV', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '1125520', '2025-09-25', 'dalam_pengerjaan', '13', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('53', '23', 'BRS', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '159586', '2023-08-06', 'disetujui', '19', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('54', '6', 'LDV', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '258769', '2024-02-18', 'disetujui', '19', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('55', '10', 'BRS', 'Konsep Art Makhluk Fantasi', 'Makhluk mitologi atau imajinatif dalam bentuk digital.', '772654', '2023-03-17', 'dalam_pengerjaan', '14', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('56', '12', 'ZHC', 'Lukisan Digital Pemandangan', 'Lukisan pemandangan alam dengan gaya semi-realistis.', '778316', '2025-01-24', 'menunggu_persetujuan', '19', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('57', '4', 'BRS', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '116867', '2023-07-15', 'ditolak', '27', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('58', '12', 'ZHC', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '1383619', '2023-12-16', 'disetujui', '15', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('59', '17', 'ZHC', 'Ilustrasi Tema Musik', 'Ilustrasi karakter dengan suasana konser atau musik.', '316579', '2024-12-14', 'disetujui', '29', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('60', '25', 'ZHC', 'Lukisan Digital Pemandangan', 'Lukisan pemandangan alam dengan gaya semi-realistis.', '865961', '2023-04-16', 'ditolak', '14', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('61', '1', 'ZHC', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '1167665', '2024-01-07', 'disetujui', '22', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('62', '21', 'ZHC', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '1230777', '2024-12-31', 'disetujui', '7', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('63', '22', 'BRS', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '1476443', '2024-09-15', 'dalam_pengerjaan', '15', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('64', '20', 'BRS', 'Lukisan Digital Pemandangan', 'Lukisan pemandangan alam dengan gaya semi-realistis.', '811482', '2024-11-11', 'menunggu_persetujuan', '27', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('65', '23', 'BRS', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '996691', '2024-04-30', 'ditolak', '9', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('66', '22', 'LDV', 'Lukisan Digital Pemandangan', 'Lukisan pemandangan alam dengan gaya semi-realistis.', '351089', '2023-11-27', 'disetujui', '6', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('67', '19', 'LDV', 'Chibi Karakter Band', 'Versi chibi lucu dari empat anggota band virtual.', '750859', '2025-04-13', 'selesai', '17', '2025-04-10', '299', 'Hasil sangat memuaskan dan profesional!');
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('68', '16', 'LDV', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '1394207', '2023-09-20', 'ditolak', '4', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('69', '11', 'BRS', 'Chibi Karakter Band', 'Versi chibi lucu dari empat anggota band virtual.', '215483', '2025-07-05', 'selesai', '13', '2025-07-04', '808', NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('70', '12', 'ZHC', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '601839', '2025-07-12', 'menunggu_persetujuan', '15', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('71', '2', 'BRS', 'Lukisan Digital Pemandangan', 'Lukisan pemandangan alam dengan gaya semi-realistis.', '865230', '2023-01-16', 'ditolak', '23', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('72', '5', 'LDV', 'Chibi Karakter Band', 'Versi chibi lucu dari empat anggota band virtual.', '1227092', '2024-03-25', 'selesai', '22', '2024-03-20', '988', 'Proses cepat dan komunikatif.');
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('73', '14', 'ZHC', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '11725', '2023-02-02', 'ditolak', '24', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('74', '20', 'ZHC', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '51454', '2025-03-15', 'selesai', '13', '2025-03-14', '111', 'Gaya visualnya unik dan berkarakter.');
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('75', '3', 'LDV', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '569695', '2024-06-21', 'disetujui', '5', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('76', '6', 'LDV', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '1379683', '2023-10-04', 'ditolak', '24', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('77', '23', 'BRS', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '1478590', '2023-10-25', 'disetujui', '22', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('78', '21', 'ZHC', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '1314545', '2023-08-13', 'ditolak', '4', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('79', '24', 'ZHC', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '1175534', '2024-03-07', 'dalam_pengerjaan', '20', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('80', '24', 'LDV', 'Visualisasi Karakter RPG', 'Desain karakter untuk proyek game role-playing.', '1271286', '2024-09-23', 'dalam_pengerjaan', '8', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('81', '22', 'BRS', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '697740', '2023-10-29', 'ditolak', '10', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('82', '8', 'ZHC', 'Ilustrasi Karakter Fantasi', 'Gambarkan karakter orisinal dengan tema dunia fantasi.', '1133499', '2025-06-23', 'menunggu_persetujuan', '16', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('83', '10', 'BRS', 'Chibi Karakter Band', 'Versi chibi lucu dari empat anggota band virtual.', '238686', '2025-04-30', 'menunggu_persetujuan', '4', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('84', '4', 'ZHC', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '511135', '2023-12-11', 'disetujui', '18', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('85', '22', 'BRS', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '657577', '2023-01-31', 'ditolak', '22', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('86', '20', 'BRS', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '50856', '2025-05-08', 'selesai', '25', '2025-05-06', '811', 'Gaya visualnya unik dan berkarakter.');
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('87', '12', 'ZHC', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '525609', '2025-04-06', 'menunggu_persetujuan', '15', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('88', '11', 'LDV', 'Konsep Art Makhluk Fantasi', 'Makhluk mitologi atau imajinatif dalam bentuk digital.', '696314', '2025-01-17', 'dalam_pengerjaan', '20', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('89', '4', 'LDV', 'Ilustrasi Karakter Fantasi', 'Gambarkan karakter orisinal dengan tema dunia fantasi.', '532642', '2025-07-06', 'menunggu_persetujuan', '18', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('90', '14', 'ZHC', 'Ilustrasi Karakter Fantasi', 'Gambarkan karakter orisinal dengan tema dunia fantasi.', '131312', '2025-07-28', 'disetujui', '10', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('91', '21', 'LDV', 'Konsep Art Makhluk Fantasi', 'Makhluk mitologi atau imajinatif dalam bentuk digital.', '469993', '2024-12-02', 'selesai', '25', '2024-11-29', '763', NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('92', '1', 'ZHC', 'Ilustrasi Karakter Fantasi', 'Gambarkan karakter orisinal dengan tema dunia fantasi.', '738324', '2025-01-05', 'disetujui', '24', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('93', '17', 'LDV', 'Visualisasi Karakter RPG', 'Desain karakter untuk proyek game role-playing.', '1158153', '2025-07-28', 'selesai', '18', '2025-07-14', '301', 'Ilustrasinya keren, sesuai request!');
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('94', '21', 'LDV', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '1123310', '2023-01-16', 'ditolak', '15', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('95', '18', 'LDV', 'Konsep Art Makhluk Fantasi', 'Makhluk mitologi atau imajinatif dalam bentuk digital.', '696527', '2025-07-18', 'disetujui', '25', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('96', '25', 'LDV', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '82871', '2025-07-06', 'menunggu_persetujuan', '23', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('97', '11', 'BRS', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '1345601', '2023-11-20', 'dalam_pengerjaan', '30', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('98', '11', 'BRS', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '387752', '2023-07-23', 'ditolak', '30', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('99', '15', 'BRS', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '1091402', '2024-03-01', 'dalam_pengerjaan', '6', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('100', '20', 'BRS', 'Konsep Art Makhluk Fantasi', 'Makhluk mitologi atau imajinatif dalam bentuk digital.', '910674', '2023-06-03', 'disetujui', '20', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('101', '3', 'LDV', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '1197874', '2025-02-06', 'menunggu_persetujuan', '20', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('102', '22', 'LDV', 'Konsep Art Makhluk Fantasi', 'Makhluk mitologi atau imajinatif dalam bentuk digital.', '909828', '2024-06-09', 'disetujui', '3', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('103', '25', 'ZHC', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '1448471', '2025-07-21', 'dalam_pengerjaan', '26', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('104', '15', 'LDV', 'Visualisasi Karakter RPG', 'Desain karakter untuk proyek game role-playing.', '380372', '2024-08-29', 'disetujui', '28', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('105', '18', 'BRS', 'Ilustrasi Karakter Fantasi', 'Gambarkan karakter orisinal dengan tema dunia fantasi.', '1386626', '2023-10-28', 'ditolak', '25', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('106', '3', 'BRS', 'Lukisan Digital Pemandangan', 'Lukisan pemandangan alam dengan gaya semi-realistis.', '564940', '2024-11-07', 'dalam_pengerjaan', '18', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('107', '22', 'ZHC', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '1187115', '2024-05-21', 'selesai', '27', '2024-05-11', '609', 'Gaya visualnya unik dan berkarakter.');
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('108', '9', 'BRS', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '622535', '2025-10-08', 'selesai', '19', '2025-10-08', '744', 'Revisi langsung dikerjakan, mantap.');
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('109', '6', 'BRS', 'Lukisan Digital Pemandangan', 'Lukisan pemandangan alam dengan gaya semi-realistis.', '833921', '2024-03-13', 'ditolak', '11', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('110', '19', 'BRS', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '880539', '2025-04-15', 'menunggu_persetujuan', '17', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('111', '2', 'LDV', 'Konsep Art Makhluk Fantasi', 'Makhluk mitologi atau imajinatif dalam bentuk digital.', '243115', '2025-01-18', 'dalam_pengerjaan', '6', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('112', '9', 'LDV', 'Visualisasi Karakter RPG', 'Desain karakter untuk proyek game role-playing.', '1074505', '2025-02-24', 'menunggu_persetujuan', '15', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('113', '12', 'ZHC', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '890422', '2023-05-01', 'ditolak', '5', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('114', '19', 'BRS', 'Visualisasi Karakter RPG', 'Desain karakter untuk proyek game role-playing.', '1325402', '2023-09-23', 'disetujui', '24', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('115', '10', 'BRS', 'Ilustrasi Tema Musik', 'Ilustrasi karakter dengan suasana konser atau musik.', '1157543', '2025-07-23', 'menunggu_persetujuan', '27', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('116', '9', 'BRS', 'Chibi Karakter Band', 'Versi chibi lucu dari empat anggota band virtual.', '447210', '2024-08-30', 'disetujui', '24', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('117', '23', 'LDV', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '1075315', '2023-03-13', 'ditolak', '30', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('118', '21', 'ZHC', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '185022', '2024-01-03', 'disetujui', '14', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('119', '13', 'BRS', 'Chibi Karakter Band', 'Versi chibi lucu dari empat anggota band virtual.', '1163483', '2025-02-02', 'menunggu_persetujuan', '16', NULL, NULL, NULL);
INSERT INTO OrderSpecialContent (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, status_pengerjaan, estimasi_pengerjaan, tanggal_penyelesaian, id_konten, feedback) VALUES ('120', '22', 'ZHC', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '1420395', '2024-01-29', 'disetujui', '23', NULL, NULL, NULL);