CREATE TABLE OrderSpecialContent (
    id_order	VARCHAR(3) PRIMARY KEY NOT NULL,
    id_suporter	VARCHAR(3) NOT NULL,
    id_creator	VARCHAR(3) NOT NULL,
    judul	VARCHAR(512) NOT NULL,
    deskripsi	VARCHAR(512),
    harga_dasar	INT,
    tgl_batas_revisi	VARCHAR(512),
    feedback	VARCHAR(512),
    estimasi_pengerjaan	INT
    FOREIGN KEY (id_suporter)
        REFERENCES Suporter(id_suporter)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (id_creator)
        REFERENCES Creator(id_creator)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('001', '4', 'BRS', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '878012', '2023-04-17', 'Hasil sangat memuaskan dan profesional!', '8');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('002', '17', 'BRS', 'Visualisasi Karakter RPG', 'Desain karakter untuk proyek game role-playing.', '289584', '2025-04-17', '', '7');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('003', '3', 'ZHC', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '1355541', '2025-05-26', 'Revisi langsung dikerjakan, mantap.', '20');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('004', '7', 'ZHC', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '1486971', '2025-03-26', 'Ilustrasinya keren, sesuai request!', '23');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('005', '19', 'ZHC', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '997771', '2024-09-24', '', '21');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('006', '17', 'ZHC', 'Ilustrasi Karakter Fantasi', 'Gambarkan karakter orisinal dengan tema dunia fantasi.', '275121', '2023-09-26', 'Ilustrasinya keren, sesuai request!', '29');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('007', '20', 'BRS', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '1487298', '2023-05-21', 'Proses cepat dan komunikatif.', '14');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('008', '8', 'ZHC', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '1234294', '2024-10-15', '', '7');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('009', '15', 'ZHC', 'Konsep Art Makhluk Fantasi', 'Makhluk mitologi atau imajinatif dalam bentuk digital.', '1181819', '2024-02-27', '', '4');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('010', '23', 'ZHC', 'Visualisasi Karakter RPG', 'Desain karakter untuk proyek game role-playing.', '611138', '2025-08-07', '', '6');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('011', '12', 'LDV', 'Ilustrasi Tema Musik', 'Ilustrasi karakter dengan suasana konser atau musik.', '614183', '2023-04-30', '', '21');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('012', '14', 'BRS', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '1022057', '2025-01-10', 'Ilustrasinya keren, sesuai request!', '17');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('013', '22', 'LDV', 'Chibi Karakter Band', 'Versi chibi lucu dari empat anggota band virtual.', '228360', '2025-05-10', '', '15');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('014', '11', 'LDV', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '666489', '2025-02-07', '', '22');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('015', '24', 'ZHC', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '1135374', '2024-10-21', '', '6');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('016', '24', 'BRS', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '596525', '2023-11-06', '', '14');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('017', '5', 'LDV', 'Lukisan Digital Pemandangan', 'Lukisan pemandangan alam dengan gaya semi-realistis.', '714606', '2024-09-12', '', '14');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('018', '21', 'ZHC', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '564657', '2023-06-28', '', '19');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('019', '11', 'BRS', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '648669', '2025-10-13', 'Proses cepat dan komunikatif.', '10');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('020', '10', 'LDV', 'Ilustrasi Karakter Fantasi', 'Gambarkan karakter orisinal dengan tema dunia fantasi.', '1332549', '2023-12-14', '', '7');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('021', '23', 'ZHC', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '1209226', '2023-10-05', 'Revisi langsung dikerjakan, mantap.', '26');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('022', '23', 'LDV', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '982213', '2023-08-31', 'Gaya visualnya unik dan berkarakter.', '5');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('023', '5', 'LDV', 'Ilustrasi Karakter Fantasi', 'Gambarkan karakter orisinal dengan tema dunia fantasi.', '1230465', '2025-06-01', 'Proses cepat dan komunikatif.', '5');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('024', '19', 'BRS', 'Konsep Art Makhluk Fantasi', 'Makhluk mitologi atau imajinatif dalam bentuk digital.', '174822', '2025-07-25', '', '8');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('025', '4', 'BRS', 'Visualisasi Karakter RPG', 'Desain karakter untuk proyek game role-playing.', '241859', '2023-11-05', 'Proses cepat dan komunikatif.', '10');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('026', '3', 'BRS', 'Chibi Karakter Band', 'Versi chibi lucu dari empat anggota band virtual.', '919312', '2023-02-22', 'Ilustrasinya keren, sesuai request!', '29');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('027', '23', 'BRS', 'Visualisasi Karakter RPG', 'Desain karakter untuk proyek game role-playing.', '690787', '2025-08-16', 'Hasil sangat memuaskan dan profesional!', '22');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('028', '5', 'ZHC', 'Chibi Karakter Band', 'Versi chibi lucu dari empat anggota band virtual.', '1089442', '2025-06-06', 'Gaya visualnya unik dan berkarakter.', '24');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('029', '25', 'BRS', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '892615', '2023-09-19', '', '22');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('030', '17', 'LDV', 'Konsep Art Makhluk Fantasi', 'Makhluk mitologi atau imajinatif dalam bentuk digital.', '287385', '2024-10-02', '', '24');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('031', '4', 'LDV', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '1474260', '2023-09-21', '', '7');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('032', '1', 'ZHC', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '473017', '2025-03-21', 'Gaya visualnya unik dan berkarakter.', '18');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('033', '12', 'ZHC', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '494766', '2024-11-22', '', '5');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('034', '18', 'ZHC', 'Lukisan Digital Pemandangan', 'Lukisan pemandangan alam dengan gaya semi-realistis.', '949715', '2023-01-27', '', '18');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('035', '12', 'BRS', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '837374', '2024-10-21', 'Gaya visualnya unik dan berkarakter.', '15');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('036', '14', 'ZHC', 'Ilustrasi Karakter Fantasi', 'Gambarkan karakter orisinal dengan tema dunia fantasi.', '1095375', '2025-08-16', 'Gaya visualnya unik dan berkarakter.', '20');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('037', '22', 'ZHC', 'Ilustrasi Tema Musik', 'Ilustrasi karakter dengan suasana konser atau musik.', '443824', '2025-10-30', '', '8');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('038', '11', 'BRS', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '505734', '2024-12-22', 'Proses cepat dan komunikatif.', '30');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('039', '2', 'BRS', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '1363818', '2024-09-03', '', '17');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('040', '7', 'BRS', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '745541', '2025-09-04', 'Ilustrasinya keren, sesuai request!', '15');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('041', '5', 'ZHC', 'Lukisan Digital Pemandangan', 'Lukisan pemandangan alam dengan gaya semi-realistis.', '865627', '2023-06-29', 'Ilustrasinya keren, sesuai request!', '20');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('042', '16', 'LDV', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '1217320', '2024-02-17', '', '20');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('043', '18', 'BRS', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '1328003', '2025-03-07', '', '29');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('044', '7', 'ZHC', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '1041798', '2024-02-12', 'Proses cepat dan komunikatif.', '9');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('045', '4', 'LDV', 'Visualisasi Karakter RPG', 'Desain karakter untuk proyek game role-playing.', '1155845', '2023-01-31', 'Hasil sangat memuaskan dan profesional!', '27');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('046', '21', 'BRS', 'Chibi Karakter Band', 'Versi chibi lucu dari empat anggota band virtual.', '1122794', '2025-06-11', 'Gaya visualnya unik dan berkarakter.', '30');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('047', '19', 'ZHC', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '772218', '2024-03-08', 'Ilustrasinya keren, sesuai request!', '8');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('048', '5', 'BRS', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '1401994', '2025-04-30', 'Ilustrasinya keren, sesuai request!', '19');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('049', '22', 'BRS', 'Ilustrasi Karakter Fantasi', 'Gambarkan karakter orisinal dengan tema dunia fantasi.', '893936', '2023-12-23', '', '25');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('050', '1', 'BRS', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '402486', '2024-08-13', '', '30');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('051', '22', 'BRS', 'Konsep Art Makhluk Fantasi', 'Makhluk mitologi atau imajinatif dalam bentuk digital.', '571075', '2024-07-21', 'Gaya visualnya unik dan berkarakter.', '16');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('052', '24', 'LDV', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '1125520', '2025-09-25', '', '13');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('053', '23', 'BRS', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '159586', '2023-08-06', '', '19');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('054', '6', 'LDV', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '258769', '2024-02-18', 'Revisi langsung dikerjakan, mantap.', '19');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('055', '10', 'BRS', 'Konsep Art Makhluk Fantasi', 'Makhluk mitologi atau imajinatif dalam bentuk digital.', '772654', '2023-03-17', 'Hasil sangat memuaskan dan profesional!', '14');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('056', '12', 'ZHC', 'Lukisan Digital Pemandangan', 'Lukisan pemandangan alam dengan gaya semi-realistis.', '778316', '2025-01-24', 'Ilustrasinya keren, sesuai request!', '19');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('057', '4', 'BRS', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '116867', '2023-07-15', 'Revisi langsung dikerjakan, mantap.', '27');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('058', '12', 'ZHC', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '1383619', '2023-12-16', 'Hasil sangat memuaskan dan profesional!', '15');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('059', '17', 'ZHC', 'Ilustrasi Tema Musik', 'Ilustrasi karakter dengan suasana konser atau musik.', '316579', '2024-12-14', 'Proses cepat dan komunikatif.', '29');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('060', '25', 'ZHC', 'Lukisan Digital Pemandangan', 'Lukisan pemandangan alam dengan gaya semi-realistis.', '865961', '2023-04-16', '', '14');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('061', '1', 'ZHC', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '1167665', '2024-01-07', 'Proses cepat dan komunikatif.', '22');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('062', '21', 'ZHC', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '1230777', '2024-12-31', '', '7');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('063', '22', 'BRS', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '1476443', '2024-09-15', 'Proses cepat dan komunikatif.', '15');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('064', '20', 'BRS', 'Lukisan Digital Pemandangan', 'Lukisan pemandangan alam dengan gaya semi-realistis.', '811482', '2024-11-11', '', '27');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('065', '23', 'BRS', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '996691', '2024-04-30', 'Hasil sangat memuaskan dan profesional!', '9');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('066', '22', 'LDV', 'Lukisan Digital Pemandangan', 'Lukisan pemandangan alam dengan gaya semi-realistis.', '351089', '2023-11-27', 'Revisi langsung dikerjakan, mantap.', '6');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('067', '19', 'LDV', 'Chibi Karakter Band', 'Versi chibi lucu dari empat anggota band virtual.', '750859', '2025-03-08', 'Gaya visualnya unik dan berkarakter.', '17');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('068', '16', 'LDV', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '1394207', '2023-09-20', '', '4');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('069', '11', 'BRS', 'Chibi Karakter Band', 'Versi chibi lucu dari empat anggota band virtual.', '215483', '2025-07-05', 'Ilustrasinya keren, sesuai request!', '23');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('070', '12', 'ZHC', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '601839', '2025-07-12', 'Ilustrasinya keren, sesuai request!', '15');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('071', '2', 'BRS', 'Lukisan Digital Pemandangan', 'Lukisan pemandangan alam dengan gaya semi-realistis.', '865230', '2023-01-16', 'Hasil sangat memuaskan dan profesional!', '23');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('072', '5', 'LDV', 'Chibi Karakter Band', 'Versi chibi lucu dari empat anggota band virtual.', '1227092', '2024-03-25', 'Revisi langsung dikerjakan, mantap.', '12');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('073', '14', 'ZHC', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '1172005', '2023-02-02', '', '24');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('074', '20', 'ZHC', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '51454', '2025-03-29', 'Revisi langsung dikerjakan, mantap.', '13');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('075', '3', 'LDV', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '569695', '2024-06-21', '', '5');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('076', '6', 'LDV', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '1379683', '2023-10-04', '', '24');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('077', '23', 'BRS', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '1478590', '2023-10-25', 'Proses cepat dan komunikatif.', '22');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('078', '21', 'ZHC', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '1314545', '2023-08-13', 'Revisi langsung dikerjakan, mantap.', '4');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('079', '24', 'ZHC', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '1175534', '2024-03-07', 'Revisi langsung dikerjakan, mantap.', '20');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('080', '24', 'LDV', 'Visualisasi Karakter RPG', 'Desain karakter untuk proyek game role-playing.', '1271286', '2024-09-23', '', '8');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('081', '22', 'BRS', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '697740', '2023-10-29', 'Gaya visualnya unik dan berkarakter.', '10');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('082', '8', 'ZHC', 'Ilustrasi Karakter Fantasi', 'Gambarkan karakter orisinal dengan tema dunia fantasi.', '1133499', '2025-06-23', '', '16');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('083', '10', 'BRS', 'Chibi Karakter Band', 'Versi chibi lucu dari empat anggota band virtual.', '238686', '2025-04-30', 'Hasil sangat memuaskan dan profesional!', '4');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('084', '4', 'ZHC', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '511135', '2023-12-11', '', '18');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('085', '22', 'BRS', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '657577', '2023-01-31', 'Revisi langsung dikerjakan, mantap.', '22');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('086', '20', 'BRS', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '50856', '2025-05-18', 'Hasil sangat memuaskan dan profesional!', '25');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('087', '12', 'ZHC', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '525609', '2025-04-06', 'Proses cepat dan komunikatif.', '15');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('088', '11', 'LDV', 'Konsep Art Makhluk Fantasi', 'Makhluk mitologi atau imajinatif dalam bentuk digital.', '696314', '2025-01-17', 'Hasil sangat memuaskan dan profesional!', '20');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('089', '4', 'LDV', 'Ilustrasi Karakter Fantasi', 'Gambarkan karakter orisinal dengan tema dunia fantasi.', '532642', '2025-07-06', '', '18');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('090', '14', 'ZHC', 'Ilustrasi Karakter Fantasi', 'Gambarkan karakter orisinal dengan tema dunia fantasi.', '131312', '2025-07-28', '', '10');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('091', '21', 'LDV', 'Konsep Art Makhluk Fantasi', 'Makhluk mitologi atau imajinatif dalam bentuk digital.', '469993', '2024-10-02', 'Ilustrasinya keren, sesuai request!', '25');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('092', '1', 'ZHC', 'Ilustrasi Karakter Fantasi', 'Gambarkan karakter orisinal dengan tema dunia fantasi.', '738324', '2025-01-05', 'Hasil sangat memuaskan dan profesional!', '24');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('093', '17', 'LDV', 'Visualisasi Karakter RPG', 'Desain karakter untuk proyek game role-playing.', '1158153', '2025-07-28', 'Ilustrasinya keren, sesuai request!', '18');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('094', '21', 'LDV', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '1123310', '2023-01-16', 'Hasil sangat memuaskan dan profesional!', '15');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('095', '18', 'LDV', 'Konsep Art Makhluk Fantasi', 'Makhluk mitologi atau imajinatif dalam bentuk digital.', '696527', '2025-07-18', '', '25');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('096', '25', 'LDV', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '82871', '2025-07-06', 'Hasil sangat memuaskan dan profesional!', '23');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('097', '11', 'BRS', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '1345601', '2023-11-20', '', '30');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('098', '11', 'BRS', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '387752', '2023-07-23', '', '30');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('099', '15', 'BRS', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '1091402', '2024-03-01', 'Proses cepat dan komunikatif.', '6');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('100', '20', 'BRS', 'Konsep Art Makhluk Fantasi', 'Makhluk mitologi atau imajinatif dalam bentuk digital.', '910674', '2023-06-03', '', '20');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('101', '3', 'LDV', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '1197874', '2025-02-06', '', '20');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('102', '22', 'LDV', 'Konsep Art Makhluk Fantasi', 'Makhluk mitologi atau imajinatif dalam bentuk digital.', '909828', '2024-06-09', 'Hasil sangat memuaskan dan profesional!', '3');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('103', '25', 'ZHC', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '1448471', '2025-07-21', 'Gaya visualnya unik dan berkarakter.', '26');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('104', '15', 'LDV', 'Visualisasi Karakter RPG', 'Desain karakter untuk proyek game role-playing.', '380372', '2024-08-29', 'Proses cepat dan komunikatif.', '28');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('105', '18', 'BRS', 'Ilustrasi Karakter Fantasi', 'Gambarkan karakter orisinal dengan tema dunia fantasi.', '1386626', '2023-10-28', '', '25');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('106', '3', 'BRS', 'Lukisan Digital Pemandangan', 'Lukisan pemandangan alam dengan gaya semi-realistis.', '564940', '2024-11-07', '', '18');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('107', '22', 'ZHC', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '1187115', '2024-05-21', 'Hasil sangat memuaskan dan profesional!', '27');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('108', '9', 'BRS', 'Desain Background Cerita', 'Latar belakang untuk digunakan dalam panel cerita visual.', '622535', '2025-10-08', 'Revisi langsung dikerjakan, mantap.', '19');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('109', '6', 'BRS', 'Lukisan Digital Pemandangan', 'Lukisan pemandangan alam dengan gaya semi-realistis.', '833921', '2024-03-13', 'Gaya visualnya unik dan berkarakter.', '11');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('110', '19', 'BRS', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '880539', '2025-04-15', '', '17');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('111', '2', 'LDV', 'Konsep Art Makhluk Fantasi', 'Makhluk mitologi atau imajinatif dalam bentuk digital.', '243115', '2025-01-18', '', '6');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('112', '9', 'LDV', 'Visualisasi Karakter RPG', 'Desain karakter untuk proyek game role-playing.', '1074505', '2025-02-24', 'Revisi langsung dikerjakan, mantap.', '15');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('113', '12', 'ZHC', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '890422', '2023-05-01', 'Proses cepat dan komunikatif.', '5');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('114', '19', 'BRS', 'Visualisasi Karakter RPG', 'Desain karakter untuk proyek game role-playing.', '1325402', '2023-09-23', '', '24');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('115', '10', 'BRS', 'Ilustrasi Tema Musik', 'Ilustrasi karakter dengan suasana konser atau musik.', '1157543', '2025-07-23', '', '27');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('116', '9', 'BRS', 'Chibi Karakter Band', 'Versi chibi lucu dari empat anggota band virtual.', '447210', '2024-08-30', 'Ilustrasinya keren, sesuai request!', '24');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('117', '23', 'LDV', 'Fanart Karakter Anime', 'Gambar ulang karakter anime favorit dalam gaya Anda.', '1075315', '2023-03-13', 'Ilustrasinya keren, sesuai request!', '30');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('118', '21', 'ZHC', 'Desain Poster Event', 'Poster untuk promosi acara fiksi dengan elemen visual kuat.', '185022', '2024-01-03', '', '14');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('119', '13', 'BRS', 'Chibi Karakter Band', 'Versi chibi lucu dari empat anggota band virtual.', '1163483', '2025-02-02', 'Revisi langsung dikerjakan, mantap.', '16');
INSERT INTO tableName (id_order, id_suporter, id_creator, judul, deskripsi, harga_dasar, tgl_batas_revisi, feedback, estimasi_pengerjaan) VALUES ('120', '22', 'ZHC', 'Sampul Komik Digital', 'Desain sampul untuk komik digital bertema petualangan.', '1420395', '2024-01-29', 'Ilustrasinya keren, sesuai request!', '23');
